# Generated by Django 4.2.23 on 2025-07-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='课题编号')),
                ('name', models.CharField(max_length=255, verbose_name='课题名称')),
                ('ownership', models.CharField(choices=[('西勘院', '西勘院'), ('地下空间', '地下空间')], max_length=20, verbose_name='课题归属')),
                ('managing_unit', models.CharField(blank=True, max_length=100, verbose_name='归口单位')),
                ('level', models.CharField(choices=[('国家级', '国家级'), ('省部级', '省部级'), ('公司级', '公司级')], max_length=20, verbose_name='课题级别')),
                ('project_type', models.CharField(choices=[('应用研究', '应用研究'), ('试验发展', '试验发展')], max_length=20, verbose_name='课题类型')),
                ('role', models.CharField(choices=[('牵头', '牵头'), ('参与', '参与')], max_length=20, verbose_name='参与角色')),
                ('start_year', models.IntegerField(db_index=True, verbose_name='开始年份')),
                ('status', models.CharField(db_index=True, max_length=50, verbose_name='课题状态')),
                ('contact_person', models.CharField(blank=True, max_length=50, verbose_name='课题联系人')),
                ('project_lead', models.CharField(blank=True, max_length=50, verbose_name='课题负责人')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('planned_end_date', models.DateField(blank=True, null=True, verbose_name='计划结束日期')),
                ('extension_date', models.DateField(blank=True, null=True, verbose_name='延期时间')),
                ('actual_completion_date', models.DateField(blank=True, null=True, verbose_name='实际结题时间')),
                ('total_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='总预算(万元)')),
                ('external_funding', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='外部专项经费(万元)')),
                ('institute_funding', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='院自筹经费(万元)')),
                ('unit_funding', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='所属单位自筹经费(万元)')),
                ('research_content', models.TextField(blank=True, verbose_name='主要研究内容')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('directory_path', models.CharField(max_length=512, verbose_name='物理目录相对路径')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '科研课题',
                'verbose_name_plural': '科研课题',
                'ordering': ['-start_year', 'project_id'],
            },
        ),
    ]
