# Generated by Django 4.2.23 on 2025-07-23 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('research_content', '研究内容分析'), ('output_metrics', '产出指标分析')], max_length=20, verbose_name='分析类型')),
                ('file_name', models.CharField(max_length=255, verbose_name='分析文件名')),
                ('file_size', models.IntegerField(blank=True, null=True, verbose_name='文件大小(字节)')),
                ('analysis_result', models.TextField(verbose_name='分析结果')),
                ('confidence_score', models.FloatField(blank=True, help_text='AI分析结果的置信度，0-1之间', null=True, verbose_name='置信度分数')),
                ('processing_time', models.FloatField(blank=True, null=True, verbose_name='处理时间(秒)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='core.project', verbose_name='关联课题')),
            ],
            options={
                'verbose_name': '课题分析',
                'verbose_name_plural': '课题分析',
                'ordering': ['-created_at'],
                'unique_together': {('project', 'analysis_type')},
            },
        ),
    ]
