# Generated by Django 4.2.23 on 2025-07-23 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_projectanalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(choices=[('deepseek', 'DeepSeek'), ('kimi', 'Kimi (Moonshot)')], max_length=20, unique=True, verbose_name='AI服务')),
                ('api_key', models.TextField(verbose_name='API密钥')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用状态')),
                ('test_success', models.BooleanField(default=False, verbose_name='测试通过')),
                ('last_test_time', models.DateTimeField(blank=True, null=True, verbose_name='最后测试时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'AI API配置',
                'verbose_name_plural': 'AI API配置',
                'ordering': ['service_name'],
            },
        ),
    ]
