# Generated by Django 4.2.23 on 2025-08-02 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_apiconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('technical', '技术成果指标'), ('academic', '学术成果指标'), ('standard', '标准制定指标'), ('talent', '人才培养指标'), ('economic', '经济效益指标')], max_length=20, verbose_name='指标分类')),
                ('item_name', models.CharField(max_length=255, verbose_name='指标项目名称')),
                ('target_value', models.CharField(max_length=100, verbose_name='目标值')),
                ('current_value', models.CharField(blank=True, max_length=100, verbose_name='当前值')),
                ('status', models.CharField(choices=[('pending', '待完成'), ('in_progress', '进行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='完成状态')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='截止时间')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics_items', to='core.projectanalysis', verbose_name='关联分析')),
            ],
            options={
                'verbose_name': '产出指标项目',
                'verbose_name_plural': '产出指标项目',
                'ordering': ['category', 'item_name'],
            },
        ),
    ]
