# Generated by Django 4.2.23 on 2026-01-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_metricsitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('应用研究', '应用研究'), ('试验发展', '试验发展'), ('全自筹课题', '全自筹课题')], max_length=20, verbose_name='课题类型'),
        ),
    ]
