# Generated by Django 4.2.23 on 2026-02-05 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_project_project_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file', models.CharField(max_length=512, verbose_name='数据来源文件')),
                ('sheet_name', models.CharField(default='Sheet2', max_length=50, verbose_name='工作表')),
                ('file_mtime', models.DateTimeField(blank=True, null=True, verbose_name='文件更新时间')),
                ('threshold', models.FloatField(default=0.85, verbose_name='匹配阈值')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='导入时间')),
            ],
            options={
                'verbose_name': '支出数据导入',
                'verbose_name_plural': '支出数据导入',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255, verbose_name='课题名称')),
                ('company_name', models.CharField(blank=True, max_length=100, verbose_name='公司名称')),
                ('matched_description', models.TextField(blank=True, verbose_name='匹配描述')),
                ('match_score', models.FloatField(blank=True, null=True, verbose_name='匹配分数')),
                ('total_expense', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='累计支出')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立时间')),
                ('import_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='core.expenseimport', verbose_name='导入批次')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_snapshots', to='core.project', verbose_name='关联课题')),
            ],
            options={
                'verbose_name': '支出快照',
                'verbose_name_plural': '支出快照',
                'ordering': ['-created_at'],
            },
        ),
    ]
