# Generated by Django 4.2.23 on 2026-02-05 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_expenseimport_expensesnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_text', models.TextField(verbose_name='原始描述')),
                ('normalized_text', models.CharField(max_length=512, unique=True, verbose_name='标准化描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_mappings', to='core.project', verbose_name='匹配课题')),
            ],
            options={
                'verbose_name': '手工映射规则',
                'verbose_name_plural': '手工映射规则',
                'ordering': ['-updated_at'],
            },
        ),
    ]
