# Generated by Django 4.2.23 on 2026-08-04 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0010_operationlog"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="metricsitem",
            options={
                "ordering": ["sort_order", "category", "item_name"],
                "verbose_name": "产出指标项目",
                "verbose_name_plural": "产出指标项目",
            },
        ),
        migrations.AddField(
            model_name="metricsitem",
            name="actual_completion_date",
            field=models.DateField(blank=True, null=True, verbose_name="实际完成日期"),
        ),
        migrations.AddField(
            model_name="metricsitem",
            name="assessment_method",
            field=models.CharField(blank=True, max_length=255, verbose_name="考核方式"),
        ),
        migrations.AddField(
            model_name="metricsitem",
            name="extraction_source",
            field=models.CharField(
                choices=[
                    ("ai", "AI提取"),
                    ("manual", "手动录入"),
                    ("legacy", "历史数据"),
                ],
                default="manual",
                max_length=20,
                verbose_name="数据来源",
            ),
        ),
        migrations.AddField(
            model_name="metricsitem",
            name="planned_period",
            field=models.CharField(blank=True, max_length=100, verbose_name="计划时间"),
        ),
        migrations.AddField(
            model_name="metricsitem",
            name="progress_percent",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="完成进度(%)"
            ),
        ),
        migrations.AddField(
            model_name="metricsitem",
            name="responsible_person",
            field=models.CharField(blank=True, max_length=100, verbose_name="责任人"),
        ),
        migrations.AddField(
            model_name="metricsitem",
            name="sort_order",
            field=models.PositiveIntegerField(default=0, verbose_name="排序"),
        ),
        migrations.AddField(
            model_name="metricsitem",
            name="source_page",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="任务书来源页码"
            ),
        ),
        migrations.AddField(
            model_name="metricsitem",
            name="source_section",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="任务书来源章节"
            ),
        ),
        migrations.AddField(
            model_name="projectanalysis",
            name="source_relative_path",
            field=models.CharField(
                blank=True,
                help_text="分析来源位于课题文件目录内时记录其相对路径。",
                max_length=512,
                verbose_name="课题文件相对路径",
            ),
        ),
        migrations.AddField(
            model_name="projectanalysis",
            name="structured_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="保留从任务书中提取的目标、研究内容、指标及进度等结构化数据。",
                verbose_name="结构化分析数据",
            ),
        ),
        migrations.AlterField(
            model_name="metricsitem",
            name="category",
            field=models.CharField(
                choices=[
                    ("deliverable", "任务书考核指标"),
                    ("benefit", "经济与社会效益"),
                    ("milestone", "阶段进度目标"),
                    ("technical", "技术成果指标"),
                    ("academic", "学术成果指标"),
                    ("standard", "标准制定指标"),
                    ("talent", "人才培养指标"),
                    ("economic", "经济效益指标"),
                    ("other", "其他指标"),
                ],
                max_length=20,
                verbose_name="指标分类",
            ),
        ),
        migrations.CreateModel(
            name="MetricEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relative_path",
                    models.CharField(max_length=512, verbose_name="课题文件相对路径"),
                ),
                (
                    "display_name",
                    models.CharField(max_length=255, verbose_name="文件名"),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="佐证说明"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="关联时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="metric_evidence_links",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="关联人",
                    ),
                ),
                (
                    "metric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_files",
                        to="core.metricsitem",
                        verbose_name="关联指标",
                    ),
                ),
            ],
            options={
                "verbose_name": "指标佐证文件",
                "verbose_name_plural": "指标佐证文件",
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="metricevidence",
            constraint=models.UniqueConstraint(
                fields=("metric", "relative_path"), name="unique_metric_evidence_path"
            ),
        ),
    ]
