# Generated by Django 4.2.23 on 2026-09-21 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_project_funding_category_and_expense_snapshot_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='external_funding',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='外部专项'),
        ),
        migrations.AlterField(
            model_name='project',
            name='institute_funding',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='院专项'),
        ),
        migrations.AlterField(
            model_name='project',
            name='total_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='总预算'),
        ),
        migrations.AlterField(
            model_name='project',
            name='unit_funding',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='单位自筹'),
        ),
    ]
