# Generated by Django 4.2.23 on 2026-09-21 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_project_external_funding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensesnapshot',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_snapshots', to='core.project', verbose_name='关联课题'),
        ),
    ]
