# Generated by Django 4.2.23 on 2026-09-21 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0021_snapshot_project_set_null_and_budget_clean'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialLedgerImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledger_type', models.CharField(choices=[('external', '外部立项课题'), ('institute', '院自主立项课题')], db_index=True, max_length=20, verbose_name='台账类别')),
                ('source_file', models.CharField(max_length=512, verbose_name='数据来源文件')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='原始文件名')),
                ('file_sha256', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='文件哈希')),
                ('format_version', models.CharField(default='special-ledger-v1', max_length=50, verbose_name='数据口径版本')),
                ('sheet_name', models.CharField(default='汇总表', max_length=50, verbose_name='工作表')),
                ('row_total', models.PositiveIntegerField(default=0, verbose_name='台账课题数')),
                ('matched_total', models.PositiveIntegerField(default=0, verbose_name='已关联课题数')),
                ('ambiguous_total', models.PositiveIntegerField(default=0, verbose_name='待确认课题数')),
                ('ignored_total', models.PositiveIntegerField(default=0, verbose_name='忽略课题数')),
                ('totals', models.JSONField(blank=True, default=dict, verbose_name='汇总金额(万元)')),
                ('file_mtime', models.DateTimeField(blank=True, null=True, verbose_name='文件更新时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='导入时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='special_ledger_imports', to=settings.AUTH_USER_MODEL, verbose_name='导入人')),
            ],
            options={
                'verbose_name': '专项经费台账导入',
                'verbose_name_plural': '专项经费台账导入',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpecialLedgerRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledger_type', models.CharField(db_index=True, max_length=20, verbose_name='台账类别')),
                ('row_number', models.PositiveIntegerField(default=0, verbose_name='源表行号')),
                ('sequence', models.CharField(blank=True, max_length=50, verbose_name='台账序号')),
                ('ledger_name', models.CharField(max_length=255, verbose_name='台账课题名称')),
                ('owning_unit', models.CharField(blank=True, max_length=100, verbose_name='归属单位')),
                ('funder', models.CharField(blank=True, max_length=100, verbose_name='经费来源')),
                ('ledger_status', models.CharField(blank=True, max_length=50, verbose_name='台账研发进度')),
                ('principal', models.CharField(blank=True, max_length=50, verbose_name='课题负责人')),
                ('start_text', models.CharField(blank=True, max_length=50, verbose_name='开始时间')),
                ('end_text', models.CharField(blank=True, max_length=50, verbose_name='结束时间')),
                ('match_state', models.CharField(choices=[('exact', '同名唯一匹配'), ('manual', '人工指定'), ('ambiguous', '系统重名待确认'), ('unmatched', '系统无此课题')], db_index=True, default='unmatched', max_length=20, verbose_name='匹配情况')),
                ('contract_total', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='课题合同经费')),
                ('contract_allocated', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='归属本院合同经费')),
                ('received_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='已到账经费')),
                ('approved_budget', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='预算额度')),
                ('executed_total', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='总执行额度')),
                ('remaining_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='可支出经费')),
                ('year_disposable', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='本年度可支配经费')),
                ('year_budget', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='本年预算额')),
                ('year_executed', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='本年执行额度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立时间')),
                ('import_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='core.specialledgerimport', verbose_name='导入批次')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='special_ledger_rows', to='core.project', verbose_name='关联课题')),
            ],
            options={
                'verbose_name': '专项经费台账明细',
                'verbose_name_plural': '专项经费台账明细',
                'ordering': ['ledger_type', 'row_number'],
            },
        ),
        migrations.CreateModel(
            name='SpecialLedgerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledger_type', models.CharField(choices=[('external', '外部立项课题'), ('institute', '院自主立项课题')], max_length=20, verbose_name='台账类别')),
                ('ledger_name', models.CharField(max_length=255, verbose_name='台账课题名称')),
                ('normalized_name', models.CharField(max_length=255, verbose_name='标准化名称')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='确认时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='special_ledger_assignments', to=settings.AUTH_USER_MODEL, verbose_name='确认人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_ledger_assignments', to='core.project', verbose_name='对应课题')),
            ],
            options={
                'verbose_name': '专项台账对应关系',
                'verbose_name_plural': '专项台账对应关系',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='specialledgerimport',
            constraint=models.UniqueConstraint(condition=models.Q(('file_sha256', ''), _negated=True), fields=('ledger_type', 'file_sha256'), name='unique_special_ledger_file_hash'),
        ),
        migrations.AddConstraint(
            model_name='specialledgerassignment',
            constraint=models.UniqueConstraint(fields=('ledger_type', 'normalized_name'), name='unique_special_ledger_assignment'),
        ),
    ]
