# Generated by Django 4.2.23 on 2026-09-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_special_ledger_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialledgerimport',
            name='ignored_detail',
            field=models.JSONField(blank=True, default=list, verbose_name='忽略课题清单'),
        ),
    ]
