# Generated by Django 4.2.23 on 2026-09-21 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_special_ledger_ignored_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialledgerrow',
            name='ledger_type',
            field=models.CharField(choices=[('external', '外部立项课题'), ('institute', '院自主立项课题')], db_index=True, max_length=20, verbose_name='台账类别'),
        ),
    ]
