# Generated by Django 4.2.23 on 2026-09-21 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_special_ledger_row_type_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialledgerrow',
            name='approved_budget',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True, verbose_name='预算额度'),
        ),
        migrations.AlterField(
            model_name='specialledgerrow',
            name='contract_allocated',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True, verbose_name='归属本院合同经费'),
        ),
        migrations.AlterField(
            model_name='specialledgerrow',
            name='contract_total',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True, verbose_name='课题合同经费'),
        ),
        migrations.AlterField(
            model_name='specialledgerrow',
            name='executed_total',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True, verbose_name='总执行额度'),
        ),
        migrations.AlterField(
            model_name='specialledgerrow',
            name='received_amount',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True, verbose_name='已到账经费'),
        ),
        migrations.AlterField(
            model_name='specialledgerrow',
            name='remaining_amount',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True, verbose_name='可支出经费'),
        ),
        migrations.AlterField(
            model_name='specialledgerrow',
            name='year_budget',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True, verbose_name='本年预算额'),
        ),
        migrations.AlterField(
            model_name='specialledgerrow',
            name='year_disposable',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True, verbose_name='本年度可支配经费'),
        ),
        migrations.AlterField(
            model_name='specialledgerrow',
            name='year_executed',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True, verbose_name='本年执行额度'),
        ),
    ]
